### ISSUE TITLE
Can't pull early round stats for Nadal in 2022

### ISSUE THREAD

**Issue by bradyb** [ragprab/tennis-stats#5]
If I update input.csv so that we try to grab the second round stats for Nadal I get the following error:
```
Error fetching URL: https://www.rolandgarros.com/en-us/matches/2022/SM019
Traceback (most recent call last):
  File "pull_tennis_stats.py", line 22, in <module>
    ts = FrenchOpenStatsCalculator(round, playerId, gender, http)
  File "/home/turist/tennis-stats/french_open_stats.py", line 51, in __init__
    self.soup = self.getMatchStats(playerId, gender, round, http)
  File "/home/turist/tennis-stats/french_open_stats.py", line 73, in getMatchStats
    self.variableMap = self.getJsVariableMap(statsScript)
  File "/home/turist/tennis-stats/french_open_stats.py", line 97, in getJsVariableMap
    startIdx = statsScript.find(searchTerm)
AttributeError: 'NoneType' object has no attribute 'find'
```

I think this happens for rounds 1-3

**Comment by ragprab** [comment]
Can you share the input.csv you used which produced this error? I tried pulling all the stats for Nadal's rounds 1-3 matches, and didn't get an error. Here's the input.csv I used:

Rafael Nadal,M,32,Serve,1
Rafael Nadal,M,32,Power,1
Rafael Nadal,M,32,Mind,1
Rafael Nadal,M,32,Defense,1
Rafael Nadal,M,32,Return,1
Rafael Nadal,M,32,Serve,2
Rafael Nadal,M,32,Power,2
Rafael Nadal,M,32,Mind,2
Rafael Nadal,M,32,Defense,2
Rafael Nadal,M,32,Return,2
Rafael Nadal,M,32,Serve,3
Rafael Nadal,M,32,Power,3
Rafael Nadal,M,32,Mind,3
Rafael Nadal,M,32,Defense,3
Rafael Nadal,M,32,Return,3

**Comment by ragprab** [comment]
That error message prints when the HTTP response has status != 200, but the printed URL is correct, so I'm guessing this is a transient error (unless it happened repeatedly for you?). I will add some code to retry the HTTP request if it fails.

**Comment by bradyb** [comment]
Ok yeah it's working for me now, must have beeen transient
